In [3]:
import torch
import numpy as np

In [9]:
data = [[1, 2], [3, 4]]
tdata = torch.tensor(data)
print(tdata, type(tdata))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [4]:
arr = np.array(data)
t_np = torch.from_numpy(arr)

In [5]:
t_ones = torch.ones_like(tdata)
print(f"Ones Tensor: \n {t_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



Overriding

In [10]:
t_rand = torch.rand_like(tdata, dtype=torch.float)
print(f"Random Tensor: \n {t_rand} \n")

Random Tensor: 
 tensor([[0.4010, 0.7717],
        [0.2630, 0.0758]]) 



Random and Constant Variables

In [11]:
shape = (3, 3,)
rand_t = torch.rand(shape)
ones_t = torch.ones(shape)
zeros_t = torch.zeros(shape)

print(f"Random Tensor: \n {rand_t} \n")
print(f"Ones Tensor: \n {ones_t} \n")
print(f"Zeros Tensor: \n {zeros_t}")

Random Tensor: 
 tensor([[0.5996, 0.2715, 0.1276],
        [0.3221, 0.4751, 0.9702],
        [0.5958, 0.6605, 0.6858]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [12]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operations

Scalar vector multiplication

In [13]:
a = torch.rand(1)
b = torch.rand(3, 3)
mul = torch.einsum('i, ij -> ij', [a, b])
print(a)
print(b)
print(mul)

tensor([0.1746])
tensor([[0.4379, 0.0357, 0.9728],
        [0.1647, 0.7328, 0.6303],
        [0.0430, 0.4873, 0.1860]])
tensor([[0.0765, 0.0062, 0.1699],
        [0.0288, 0.1280, 0.1101],
        [0.0075, 0.0851, 0.0325]])


Scalar dot product

In [28]:
a = torch.arange(6).reshape(3, 2)
b = torch.arange(4).reshape(2, 2)
product = torch.einsum('ij, jk ->', [a, b])
print(a)
print(b)
print(product)

tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[0, 1],
        [2, 3]])
tensor(51)


Vector vector multiplication

In [14]:
a = torch.rand(3, 5)
b = torch.rand(5, 2)
mul = torch.einsum('ij, jk -> ik', [a, b])
print(a)
print(b)
print(mul)

tensor([[0.9013, 0.8956, 0.9509, 0.1744, 0.9748],
        [0.7727, 0.2463, 0.2496, 0.7630, 0.3353],
        [0.6212, 0.0798, 0.4683, 0.0932, 0.3903]])
tensor([[0.9087, 0.5915],
        [0.0160, 0.5074],
        [0.1059, 0.4486],
        [0.0022, 0.1649],
        [0.9686, 0.7779]])
tensor([[1.8785, 2.2011],
        [1.0590, 1.0806],
        [0.9936, 0.9369]])


Outer product

In [17]:
a = torch.arange(3)
b = torch.arange(3, 7)  
product = torch.einsum('i,j -> ij', [a, b])
print(a)
print(b)
print(product)

tensor([0, 1, 2])
tensor([3, 4, 5, 6])
tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])


Hadamard product(element-wise multiplication)

In [29]:
a = torch.Tensor([[1, 2, 4], [2, 3, 1], [5, 2, 1]])
b = torch.Tensor([[5, 2, 4], [9, 4, 1], [8, 1, 6]])
product = torch.einsum("ij, ij -> ij", a, b)
print(a)
print(b)
print(product)

tensor([[1., 2., 4.],
        [2., 3., 1.],
        [5., 2., 1.]])
tensor([[5., 2., 4.],
        [9., 4., 1.],
        [8., 1., 6.]])
tensor([[ 5.,  4., 16.],
        [18., 12.,  1.],
        [40.,  2.,  6.]])


In [ ]:
# Batch matrix multiplication

a = torch.randn(3, 3, 5)
b = torch.randn(3, 5, 2)
batch_mult = torch.einsum('bij, bjk -> bik', [a, b])
print(a)
print(b)
print(batch_mult)

tensor([[[-0.6773,  0.7815,  0.0976, -0.3376, -1.0016],
         [-0.2147,  0.5441, -0.1041, -1.5888, -0.1477],
         [ 0.4789,  0.1681,  0.2626,  0.1920,  1.5456]],

        [[ 0.4644,  0.4793, -0.8845,  0.4871,  0.0896],
         [ 0.1962, -1.5146, -0.0384, -1.5082,  2.0303],
         [-0.1432, -0.8256,  2.1222, -0.7460,  1.7938]],

        [[-2.4303, -0.3767, -1.2423,  1.7091, -0.2427],
         [ 1.1554,  0.7634, -1.5851, -0.2582, -0.1536],
         [ 0.2669, -0.1670, -1.0830,  0.7396,  1.6235]]])
tensor([[[ 0.0491, -0.9551],
         [ 1.1950, -1.3534],
         [-0.3555, -0.5985],
         [-0.4036,  0.3748],
         [-0.2693, -1.0826]],

        [[-0.4017, -0.1576],
         [-1.5601,  0.5673],
         [-1.0467,  1.2570],
         [ 0.7197,  0.4947],
         [-1.7960,  0.3878]],

        [[-1.0549,  0.3017],
         [ 0.3286,  1.7896],
         [-0.3106,  0.0359],
         [-0.3485, -0.6107],
         [ 1.1762, -1.3009]]])
tensor([[[ 1.2719,  0.4887],
         [ 1.3576, -

In [ ]:
# Tensor reduction

a = torch.randn(2, 3, 5, 7)
b = torch.randn(4, 1, 3, 11, 5)
reduction = torch.einsum('pqrs, tuqvr -> pstuv', [a, b])
print(a.shape, b.shape, reduction.shape)

torch.Size([2, 3, 5, 7]) torch.Size([4, 1, 3, 11, 5]) torch.Size([2, 7, 4, 1, 11])


In [ ]:
# Transpose

a = torch.arange(8).reshape(4, 2)
transpose = torch.einsum('ij -> ji', [a])
print(a)
print(transpose)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])
tensor([[0, 2, 4, 6],
        [1, 3, 5, 7]])


In [ ]:
# Bilinear transformation

a = torch.randn(2, 3)
b = torch.randn(3, 3, 4)
c = torch.randn(2, 4)
bilinear = torch.einsum('ik, jkl, il -> ij', [a, b, c])
print(a)
print(b)
print(c)
print(bilinear)

tensor([[ 1.0194, -1.0325,  1.1552],
        [ 1.7109,  0.6803, -0.2855]])
tensor([[[-6.1467e-01,  1.1213e+00, -8.7369e-01,  7.0915e-01],
         [-2.5071e+00,  6.4044e-01, -2.8877e-01, -6.7373e-01],
         [-2.8574e-01,  2.3551e+00,  6.9576e-01,  1.7975e-01]],

        [[ 7.8964e-01,  2.2677e-01,  8.7683e-03,  1.6208e-01],
         [-1.0357e+00,  9.0935e-01, -2.6189e-01,  1.0951e+00],
         [ 6.7263e-01, -3.5130e-01,  9.0431e-01, -7.5851e-01]],

        [[ 1.2006e+00, -8.0647e-01,  1.0881e+00,  1.8557e-03],
         [ 1.5820e+00, -6.4618e-01, -2.9748e-01,  8.3277e-01],
         [ 1.0650e+00,  3.0839e-01, -8.7738e-01,  1.1741e+00]]])
tensor([[ 0.8010, -1.1297,  0.8869, -0.6142],
        [ 1.2567, -1.2474, -0.3489,  1.5471]])
tensor([[-3.1221,  5.6872,  0.4812],
        [-3.7124,  1.2538,  5.6274]])


In [ ]:
# Attention

def random_tensors(shape, num=1, requires_grad=False):
  tensors = [torch.randn(shape, requires_grad=requires_grad) for i in range(0, num)]
  return tensors[0] if num == 1 else tensors

# Parameters
# [hidden_dimension]
bM, br, w = random_tensors([7], num=3, requires_grad=True)
# [hidden_dimension x hidden_dimension]
WY, Wh, Wr, Wt = random_tensors([7, 7], num=4, requires_grad=True)

def attention(Y, ht, rt1):
  # [batch_size x hidden_dimension] 
  tmp = torch.einsum('ik, kl -> il', [ht, Wh]) + torch.einsum('ik, kl -> il', [rt1, Wr])

  Mt = torch.tanh(torch.einsum('ijk, kl -> ijl', [Y, WY]) + tmp.unsqueeze(1).expand_as(Y) + bM)
  
  # [batch_size x sequence_length]
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w])) 
  
  # [batch_size x hidden_dimension]
  rt = torch.einsum('ijk, ij -> ik', [Y, at]) + torch.tanh(torch.einsum('ij, jk -> ik', [rt1, Wt]) + br)
  
  return rt, at

# Inputs - [batch_size x sequence_length x hidden_dimension]
Y = torch.randn(3,5,7)
# [batch_size x hidden_dimension]
ht, rt1 = random_tensors([3, 7], num=2)

rt, at = attention(Y, ht, rt1)

print(at)

tensor([[0.1494, 0.3332, 0.3192, 0.1044, 0.0939],
        [0.0530, 0.5588, 0.2151, 0.0731, 0.1000],
        [0.2654, 0.0522, 0.3481, 0.2986, 0.0356]], grad_fn=<SoftmaxBackward0>)


<ipython-input-54-0f495568e4dc>:20: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  at = torch.nn.functional.softmax(torch.einsum('ijk, k -> ij', [Mt, w]))


In [ ]:
# Treeqn

def transition(zl):
  # [batch_size x num_actions x hidden_dimension]
  return zl.unsqueeze(1) + torch.tanh(torch.einsum('bk, aki -> bai', [zl, W]) + b)

# Inputs - [batch_size x hidden_dimension]
zl = torch.randn(2, 3)
# Parameters - [num_actions x hidden_dimension]
b = torch.randn(5, 3)
# Actions - [num_actions x hidden_dimension x hidden_dimension]
W = torch.randn(5, 3, 3)

transition(zl)

tensor([[[ 0.7924, -0.5440,  1.1019],
         [-0.7051, -0.2637, -0.3537],
         [-0.8080,  1.0011,  1.4171],
         [-0.2296, -0.1790,  1.2798],
         [ 1.0797,  0.5839, -0.2840]],

        [[ 0.0376, -1.3244,  0.5081],
         [-0.2335, -1.2459,  0.0876],
         [-1.0806, -0.3098,  1.3159],
         [-0.1106, -0.8778, -0.0471],
         [ 0.5811,  0.4377, -0.5074]]])